import keymirror from "keymirror";

const TYPES = keymirror({
  FETCHING_CHARACTERS: null,
  FETCHING_PLANETS: null,
  FETCHING_STARSHIPS: null,
  FETCH_CHARACTERS_SUCCESS: null,
  FETCH_CHARACTERS_FAILURE: null,
  FETCH_PLANETS_SUCCESS: null,
  FETCH_PLANETS_FAILURE: null,
  FETCH_STARSHIPS_SUCCESS: null,
  FETCH_STARSHIPS_FAILURE: null,
  FETCHING_CHARACTER: null,
  FETCH_CHARACTER_SUCCESS: null,
  FETCH_CHARACTER_FAILURE: null,
  FETCHING_PLANET: null,
  FETCH_PLANET_SUCCESS: null,
  FETCH_PLANET_FAILURE: null,
  FETCHING_STARSHIP: null,
  FETCH_STARSHIP_SUCCESS: null,
  FETCH_STARSHIP_FAILURE: null,
});

export default TYPES;
